USE [master]
GO

/****** Object:  Database [SchoolDB]    Script Date: 09/26/2017 00:15:54 ******/
CREATE DATABASE [SchoolDB] ON  PRIMARY 
( NAME = N'SchoolDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\SchoolDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SchoolDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\SchoolDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SchoolDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SchoolDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SchoolDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SchoolDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SchoolDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SchoolDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SchoolDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SchoolDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SchoolDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SchoolDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SchoolDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SchoolDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SchoolDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SchoolDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SchoolDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SchoolDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SchoolDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SchoolDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SchoolDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SchoolDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SchoolDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SchoolDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SchoolDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SchoolDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SchoolDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SchoolDB] SET  READ_WRITE 
GO

ALTER DATABASE [SchoolDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SchoolDB] SET  MULTI_USER 
GO

ALTER DATABASE [SchoolDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SchoolDB] SET DB_CHAINING OFF 
GO

